version: "3.8"

services:
    nginx:
        image: nginx:latest
        ports:
            - ${NGINX_HOST_HTTP_PORT}:80
        volumes:
            - ./:/var/www/finance-manager
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm

    php-fpm:
        build:
            dockerfile: ./docker/php-fpm/Dockerfile
        volumes:
            - ./:/var/www/finance-manager
