version: "3.8"

services:
    nginx:
        image: nginx:latest
        ports:
            - ${NGINX_HOST_HTTP_PORT}:80
        volumes:
            - ./:/var/www/finance-manager
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm

    php-fpm:
        build:
            dockerfile: ./docker/php-fpm/Dockerfile
        volumes:
            - ./:/var/www/finance-manager
        links:
            - database

    database:
        image: postgres
        ports:
            - ${DATABASE_HOST_PORT}:5432
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - ./docker/postgres/data:/var/www/lib/postgresql/data
